
export const FETCH_INGREDIENTS = 'FETCH_AVAILABLE_INGREDIENTS';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_AVAILABLE_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_ERROR = 'FETCH_AVAILABLE_INGREDIENTS_ERROR';
export const MAKE_ORDER = 'MAKE_ORDER';
export const VIEW_INGREDIENT = 'VIEW_INGREDIENT';
export const CLOSE_INGREDIENT = 'CLOSE_INGREDIENT';
export const SELECT_INGREDIENT = 'SELECT_INGREDIENT';
export const SELECT_BUN = 'SELECT_BUN';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const CHANGE_BUN = 'CHANGE_BUN';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';
export const POST_ORDER = 'POST_ORDER';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_ERROR = 'POST_ORDER_ERROR';
export const CLOSE_ORDER = 'CLOSE_ORDER';